openapi: 3.1.0
info:
  version: 1.0.0
  title: API First with Spring Boot
  termsOfService: https://example.com/terms/
  contact:
    email: john@springframework.guru
    url: http://springframework.guru/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.

    # Introduction

    guesswork in calling the service.
tags:
  - name: Customer
    description: Customer operations
  - name: Products
    description: Product operations   
  - name: User
    description: Operations about users.
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://springframework.guru/api/v1
paths:
  /users/{username}:
    $ref: paths/users_{username}.yaml
  /v1/customers:
    $ref: paths/v1/customers.yaml
  /v1/customers/{customer_id}:
    $ref: paths/v1/customers_{customer_id}.yaml
  /v1/products:
    $ref: paths/v1/products.yaml
  /v1/products/{product_id}:
    $ref: paths/v1/products_{product_id}.yaml    
security: 
  -  basic_auth: []  
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
