get: 
  tags: 
    -  Products
  summary: Get a list of products
  description: Get a list of product.
  operationId: listProducts
  responses: 
    '200': 
      description: Success
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/v1/product_list.yaml  
    '404': 
      description: Not Found
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/Problem.yaml
post:
  tags:
    - Products
  summary: Create a new product
  description: Create a new product
  operationId: createProduct
  requestBody: 
    content: 
      application/json:
        schema: 
          $ref: ../../components/schemas/v1/product.yaml
  responses: 
    '201':
      description: Created
      headers: 
        Location:
          description: Location of the new resource
          schema: 
            type: string
            example: /v1/products/ba3f300d-bdd1-4507-a16a-8559729a561a
    '400':
      description: Bad request
      content:
        applicaiton/json:
          schema:
            $ref: ../../components/schemas/Problem.yaml       
  